export * as LLMSemconv from "./semconv"

// Keep this projection synced with the OpenTelemetry semantic conventions.
// GenAI conventions are specification-only and do not publish a JavaScript package:
// https://github.com/open-telemetry/semantic-conventions-genai/blob/c321d7eb4443ae1d1d88c2e24eda849f62049008/model/gen-ai/registry.yaml

export const ATTR_ERROR_TYPE = "error.type"
export const ATTR_HTTP_REQUEST_METHOD = "http.request.method"
export const ATTR_HTTP_RESPONSE_STATUS_CODE = "http.response.status_code"
export const ATTR_NETWORK_PROTOCOL_NAME = "network.protocol.name"
export const ATTR_NETWORK_TRANSPORT = "network.transport"
export const ATTR_SERVER_ADDRESS = "server.address"
export const ATTR_SERVER_PORT = "server.port"
export const ATTR_URL_FULL = "url.full"
export const ATTR_URL_PATH = "url.path"
export const ATTR_URL_SCHEME = "url.scheme"

export const ATTR_GEN_AI_OPERATION_NAME = "gen_ai.operation.name"
export const ATTR_GEN_AI_OUTPUT_TYPE = "gen_ai.output.type"
export const ATTR_GEN_AI_PROVIDER_NAME = "gen_ai.provider.name"
export const ATTR_GEN_AI_REQUEST_FREQUENCY_PENALTY = "gen_ai.request.frequency_penalty"
export const ATTR_GEN_AI_REQUEST_MAX_TOKENS = "gen_ai.request.max_tokens"
export const ATTR_GEN_AI_REQUEST_MODEL = "gen_ai.request.model"
export const ATTR_GEN_AI_REQUEST_PRESENCE_PENALTY = "gen_ai.request.presence_penalty"
export const ATTR_GEN_AI_REQUEST_SEED = "gen_ai.request.seed"
export const ATTR_GEN_AI_REQUEST_STOP_SEQUENCES = "gen_ai.request.stop_sequences"
export const ATTR_GEN_AI_REQUEST_STREAM = "gen_ai.request.stream"
export const ATTR_GEN_AI_REQUEST_TEMPERATURE = "gen_ai.request.temperature"
export const ATTR_GEN_AI_REQUEST_TOP_K = "gen_ai.request.top_k"
export const ATTR_GEN_AI_REQUEST_TOP_P = "gen_ai.request.top_p"
export const ATTR_GEN_AI_RESPONSE_FINISH_REASONS = "gen_ai.response.finish_reasons"
export const ATTR_GEN_AI_RESPONSE_TIME_TO_FIRST_CHUNK = "gen_ai.response.time_to_first_chunk"
export const ATTR_GEN_AI_USAGE_CACHE_CREATION_INPUT_TOKENS = "gen_ai.usage.cache_creation.input_tokens"
export const ATTR_GEN_AI_USAGE_CACHE_READ_INPUT_TOKENS = "gen_ai.usage.cache_read.input_tokens"
export const ATTR_GEN_AI_USAGE_INPUT_TOKENS = "gen_ai.usage.input_tokens"
export const ATTR_GEN_AI_USAGE_OUTPUT_TOKENS = "gen_ai.usage.output_tokens"
export const ATTR_GEN_AI_USAGE_REASONING_OUTPUT_TOKENS = "gen_ai.usage.reasoning.output_tokens"
export const ATTR_GEN_AI_CONVERSATION_ID = "gen_ai.conversation.id"
export const ATTR_GEN_AI_INPUT_MESSAGES = "gen_ai.input.messages"
export const ATTR_GEN_AI_OUTPUT_MESSAGES = "gen_ai.output.messages"
export const ATTR_GEN_AI_SYSTEM_INSTRUCTIONS = "gen_ai.system_instructions"

// OpenCode extensions used alongside the upstream GenAI conventions.
export const ATTR_OPENCODE_ERROR_SOURCE = "opencode.error.source"
export const ATTR_OPENCODE_ERROR_STAGE = "opencode.error.stage"
export const ATTR_OPENCODE_LLM_PROTOCOL = "opencode.llm.protocol"
export const ATTR_OPENCODE_LLM_ROUTE = "opencode.llm.route"
export const ATTR_OPENCODE_PROVIDER_HTTP_STATUS_CODE = "opencode.provider.http.status_code"
export const ATTR_OPENCODE_PROVIDER_REQUEST_ID = "opencode.provider.request.id"
export const ATTR_OPENCODE_TRANSPORT_KIND = "opencode.transport.kind"

export const GEN_AI_OPERATION_NAME_VALUE_CHAT = "chat"
export const GEN_AI_OPERATION_NAME_VALUE_GENERATE_CONTENT = "generate_content"
export const GEN_AI_OUTPUT_TYPE_VALUE_JSON = "json"
export const GEN_AI_OUTPUT_TYPE_VALUE_TEXT = "text"
